color_dict = {
    "water": "#80ccff",
    "light_green": "#85e085",
    "forest_green": "#009933",
    "sand": "#ffffcc",
    "light_purple": "#eeccff",
    "light_gray": "#e6e6e6",
    "gray": "#cccccc",
    "yellow_farm": "#ecffb3",
    "rock": "#d9b38c",
    "red_road": "#ff5050",
    "orange_road": "#ff944d",
    "medium_orange_road": "#ffa64d",
    "light_orange_road": "#ffbf80",
    "residential_road": "#fff3e6",
    "tertiary_road": "#ffd9b3",
    "foot_path": "#ecd9c6",
    "track": "#dfbf9f",
    "salt_pond": "#eeccff",
    "unclassified_road": "#ffe6cc",
    "snow": "white",
    "black": "black",
    "no_vegetation" : "#C3BA8D"
}

highway_colors = {
    'motorway': 'red_road',
    'trunk': 'orange_road',
    'primary': 'medium_orange_road',
    'secondary': 'light_orange_road',
    'residential': 'residential_road',
    'living_street': 'residential_road',
    'service': 'residential_road',
    'tertiary': 'tertiary_road',
    'unclassified': 'unclassified_road',
    'road': 'unclassified_road',
    'track': 'track',
    'footway': 'foot_path',
    'path': 'foot_path'
}

natural_colors = {
    'wood': 'forest_green',
    'fell': 'light_green',
    'grassland': 'light_green',
    'scrub': 'light_green',
    'shrubbery': 'light_green',
    'tundra': 'light_green',
    'valley': 'light_green',
    'hill': 'light_green',
    'heath': 'light_green',
    'bay': 'water',
    'water': 'water',
    'wetland': 'light_green',
    'strait': 'water',
    'reef': 'sand',
    'shoal': 'sand',
    'beach': 'sand',
    'sand': 'sand',
    'bare_rock': 'rock',
    'bloackfield': 'rock',
    'scree': 'rock'
}

landuse_colors = {
    'paddy': 'light_green',
    'greenfield': 'light_green',
    'vineyard': 'light_green',
    'cemetery': 'light_green',
    'grass': 'light_green',
    'port': 'water',
    'basin': 'water',
    'aquaculture': 'water',
    'forest': 'forest_green',
    'greehouse_horticulture': 'light_green',
    'farmland': 'light_green',
    'meadow': 'light_green',
    'orchard': 'light_green',
    'salt_pond': 'salt_pond',
    'commercial': 'light_gray',
    'education': 'light_gray',
    'retail': 'light_gray',
    'industrial': 'gray',
    'construction': 'gray',
    'residential': 'light_purple',
    # 'military': 'gray'
}

CLC_color_mapping = {
    '1': 'gray',
    '2': 'forest_green',
    '3': 'forest_green',
    '4': 'forest_green',
    '5': 'light_green',
    '6': 'light_green',
    '7': 'light_green',
    '8': 'light_green',
    '9': 'no_vegetation',
    '10': 'water',
    '11': 'snow',
    '253': 'water',
    '254': 'water',
    '0': 'black'
}